### ISSUE TITLE
Clean it up the file `app.js`

### ISSUE THREAD

**Issue by Wolfy64** [Wolfy64/SJParks#63]
To keep the backend as simple as possible I commented some lines of codes.
Please kindly review it

**Comment by joshuaaguilar20** [comment]
I am going to take this on know and clean up the structure a bit.

**Comment by joshuaaguilar20** [comment]
do we need the lines of code that are commented out? I am just curious if they were there for a reason or if we could make a playground folder for test code etc?

**Comment by Wolfy64** [comment]
I commented it because I think we don't need it but you are more experience that me on the Backend, so I just waited your review.

**Comment by joshuaaguilar20** [comment]
Ok great I agree with a lot of it. Who wrote all that code it seems like 3
project copy pasted together? It's got sessions/tokens and a few others

**Comment by thMthMnky** [comment]
I wrote most of the BA. It looks like 3 separate projects because I used many different resources while learning. The things that I commented are mostly me holding on to things because I didn't know what worked and what didn't. I love the idea of a 'playground' folder.

**Comment by joshuaaguilar20** [comment]
Henrey,

No worries man it did not look bad. Great work, not just anybody can do
that.  I can help you fine tune this machine.
